name: ldm
dependencies:
  - pip:
    - gradio==3.1.6
    - pynvml==11.4.1
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
